"""Add description

Revision ID: 6c168d86dad6
Revises: 6cc67891f089
Create Date: 2025-05-22 19:38:43.840607

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6c168d86dad6"
down_revision = "6cc67891f089"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "description")
    # ### end Alembic commands ###
